import acerNitro5Image from "../../../assets/acer-nitro-5-an515.png";

export const mockProducts = [
    {
      _id: "1",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "2",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "3",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "4",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "5",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "6",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "7",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "8",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "9",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "10",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "1",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "2",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "3",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "4",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "5",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "6",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "7",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "8",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "9",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "10",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "1",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "2",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "3",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "4",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "5",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "6",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "7",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "8",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "9",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "10",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: acerNitro5Image,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    
];