import productImage1 from "../../../assets/product1.png";
import productImage2 from "../../../assets/product2.png";
import productImage3 from "../../../assets/product3.png";

export const mockProducts = [
    {
      _id: "1",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage1,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "2",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage1,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "3",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage1,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "4",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage1,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "5",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage1,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "6",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage1,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "7",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage1,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "8",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage1,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "9",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage1,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "10",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage1,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "11",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 1000,
      totalStock: 50,
      image: productImage2,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "12",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 1100,
      totalStock: 50,
      image: productImage2,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "13",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 1000,
      totalStock: 0,
      image: productImage2,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "14",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage2,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "15",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 0,
      image: productImage2,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "16",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage2,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "17",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage2,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "18",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage2,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "19",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage2,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "20",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage2,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "21",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage3,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "22",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage3,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "23",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage3,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "24",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage3,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "25",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage3,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "26",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage3,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "27",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage3,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "28",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage3,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "29",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage3,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    {
      _id: "30",
      name: "Laptop Acer Nitro 5",
      price: 1200,
      salePrice: 0,
      totalStock: 50,
      image: productImage3,
      rating: 4.5,
      description: "Laptop gaming hiệu năng mạnh mẽ.",
      status: "On Stock",
      createdAt: "2024-11-01T12:00:00Z",
      category_id: "1",
      brand_id: "1"
    },
    
];

export const fetchMockProducts = (page, limit) => {
    const start = (page - 1) * limit;
    const end = page * limit;
    const paginatedProducts = mockProducts.slice(start, end);
    
    return {
        products: paginatedProducts,
        totalPage: Math.ceil(mockProducts.length / limit),
        currentPage: page,
    };
};